### ISSUE TITLE
Different rules for source path in server vs. deploy mode

### ISSUE THREAD

**Issue by robinsloan** [GoogleCloudPlatform/functions-framework-ruby#112]
I just ran into a small inconsistency between the built-in server's expectations and those of Google Cloud Functions on deploy.

I've written a couple of functions and placed them in separate files in the same directory, which also contains a shared dependency. If I want to run one of those functions with the built-in server, this invocation works fine:

```
bundle exec functions-framework-ruby \
--source "admin.rb" \
--target "admin-function"
```

However, this deploy command fails --

```
gcloud functions deploy "admin-function" \
--runtime ruby27 \
--source "admin.rb" \
--trigger-http \
--allow-unauthenticated \
--region "us-west2" \
--timeout 30
```

-- with the error `ERROR: (gcloud.functions.deploy) argument --source: Provided path does not point to a directory`. And, indeed, [the docs here](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--source) seem to indicate the `deploy` command wants a directory, not a single filename. (The name of the Ruby file it looks for in that directory isn't documented, but I presume it's `app.rb`?)

So maybe it makes sense for the server preview to reject a single filename, too? Not totally sure. This just surprised me, so I thought I'd mention it.

Thanks for this framework; it's a pleasure to use!

**Comment by grant** [comment]
It's a little confusing but I don't believe the `--source` flag for the Functions Framework corresponds to the `source` flag in Cloud Functions. They mean two different things.

In this case, I believe you're using the `gcloud functions deploy` `--source` incorrectly. It's used for things like deploying from a Cloud Storage bucket, Cloud Source Repo, or different folder within your filesystem. It doesn't allow you to specify different file names like `admin.rb`.

I think you'll want to provide a `FUNCTION_TARGET` runtime env var with your desired location. I'm not sure how you're sharing the dependency, but be sure to include it in the folder you upload with gcloud.

**Comment by robinsloan** [comment]
Yes! That's the understanding I arrived at after looking through the docs.

So, this is just a user report. The ability to specify a particular source file for the built-in server made me think I'd have the same ability in deploy mode, which led to some confusion. Although, I'm now realizing that my confusion was grounded in my assumption that the built-in server is intended as a preview or staging environment, and maybe that's not entirely the case.

I'll close the issue. Thanks again!
