### ISSUE TITLE
Document Release Process

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-ruby#113]
Hi there!

We're trying to document the release process for all Function Framework repos. I couldn't find the steps needed for this repo (i.e. [CONTRIBUTING](https://github.com/GoogleCloudPlatform/functions-framework-ruby/blob/main/.github/CONTRIBUTING.md)).

Could we add the following?

- Basic docs on creating a release/tag
- Basic docs on how to publish this gem

I'm not sure how versions are cut. Maybe we could add release please?

Context: 198338889

**Comment by dazuma** [comment]
Yes, I'm in the middle getting release-please set up for this repo. There are a few challenges; it will be next week sometime.
