### ISSUE TITLE
Add Zeitwerk.

### ISSUE THREAD

**Issue by Subomi** [GoogleCloudPlatform/functions-framework-ruby#84]
A big plus for writing Rails is autoloading of constants. Adding Zeitwerk will improve the developer's productivity in building Cloud functions, I believe. 

Are there any plans for this in the future?

**Comment by dazuma** [comment]
We're not likely to include zeitwerk directly into the functions_framework itself. The framework is not a rails-style framework; we're trying to keep it lightweight. However, nothing is stopping any app from including zeitwerk itself. (Just add it to your app's own Gemfile, alongside the functions_framework gem.) Would that be sufficient for your needs?

**Comment by Subomi** [comment]
Oh yes! I can add zeitwerk to my apps directly. I only thought to ask if it was somewhere in the roadmap.

Thanks!
