### ISSUE TITLE
Do not override `functions-framework`

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-ruby#9]
I'm not sure if this is a ruby package manager issue or what exactly. I am getting a funny error:

I'm running my Node function:

```sh
 npx @google-cloud/functions-framework --target=helloWorld
```

However, I get this unrelated error:

```sh
npx @google-cloud/functions-framework --target=helloWorld
I, [2020-05-21T17:56:22.642045 #41868]  INFO -- : FunctionsFramework: Loading functions from "./app.rb"...
Traceback (most recent call last):
	4: from /Users/$USER/.rvm/gems/ruby-2.3.4/bin/functions-framework:23:in `<main>'
	3: from /Users/$USER/.rvm/gems/ruby-2.3.4/bin/functions-framework:23:in `load'
	2: from /Users/$USER/.rvm/gems/ruby-2.3.4/gems/functions_framework-0.1.1/bin/functions-framework:19:in `<top (required)>'
	1: from /Users/$USER/.rvm/gems/ruby-2.3.4/gems/functions_framework-0.1.1/lib/functions_framework/cli.rb:100:in `run'
/Users/$USER/.rvm/gems/ruby-2.3.4/gems/functions_framework-0.1.1/lib/functions_framework/cli.rb:100:in `load': cannot load such file -- ./app.rb (LoadError)
```

I'm using the Node FF, not ruby... ???

---

The fix:

```sh
gem uninstall functions_framework
```

Can we prevent this somehow?

**Comment by dazuma** [comment]
@grant  I assume this is happening because both the Node FF and the Ruby FF are installing a `functions-framework` binary in your `$PATH`, and your path just happens to have the Ruby binary directory first. Not sure what we can do about this, beyond asking all language FFs to rename their binaries to `functions-framework-${LANG}` or something like that.

**Comment by grant** [comment]
I don't think the Node FF adds a PATH for it's FF.

It's mainly an issue since I believe multiple FFs have these aliases (I know python has one) and will clash for users if they use multiple frameworks (like I observed).

I'll have to investigate more...

**Comment by hdp617** [comment]
From [0], `npx` checks if the FF is in `PATH`. It looks like if the Ruby FF is in `PATH`, `npx` will execute the Ruby FF.

[0] https://github.com/npm/npx#description

**Comment by hdp617** [comment]
> Is there a way to configure the Node FF to look for a binary with a different name?

Yes, I _think_ we can add `functions-framework-nodejs` in  [0] for Node.js.

@grant WDYT? Should this be in the FF contract?

[0] https://github.com/hdp617/functions-framework-nodejs/blob/5bf1ad161b69c82df6edf8379d9f6c8815a62843/package.json#L32

**Comment by grant** [comment]
I'm not sure I fully understand the issue.

With Ruby, installing the gem gives the global command `functions-framework`.
With Node, installing the package does not give the global command `functions-framework`.
Right?

It's a problem when a FF takes the binary `functions-framework` given we have multiple FF languages.

---

I think we should change `bin/functions-framework` to `bin/functions-framework-ruby` in this repo and try to not name binaries `functions-framework`. If the Node FF can be globally invoked with `functions-framework` (without the scope of `@google-cloud` or use of `npx`), we should probably change the binary name there too.

@hdp617 It should probably be in the contract "make binaries unique among other FF languages".
I don't understand the issue as much, do you want to create a PR?

**Comment by dazuma** [comment]
With Node, installing the package _does_ give the global command `functions-framework`, doesn't it? Otherwise how does npx work?

I'm okay with adding `functions-framework-ruby` and dropping `functions-framework`, as long as _all_ languages (that want to install a global command) do it. Otherwise, we could have the reverse issue where a Ruby user invokes `functions-framework` and gets the Node version instead.

**Comment by grant** [comment]
Node doesn't give the command `functions-framework` when installing the framework.
It's not required to install the module globally with `npm i -g`.

You use the local binary or run Node's `npx` binary first to use the framework.
Is there something equivalent in ruby? Or is it not possible/common to have a local binary.

**Comment by dazuma** [comment]
Ruby does not have the concept of a "local binary" (i.e. it has no equivalent of npx). Ruby libraries that want to install an "executable" will do so by adding it to the global path.

**Comment by grant** [comment]
> Ruby does not have the concept of a "local binary" (i.e. it has no equivalent of npx). Ruby libraries that want to install an "executable" will do so by adding it to the global path.

Got it. Thanks for explaining. I'll just close this since I don't think changing the binary to functions-framework-ruby would be worth the cost. If others run into it, we can re-open the issue.
